steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/demodirector-web:${_TAG}
      - .
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/demodirector-web:${_TAG}
substitutions:
  _REGION: us-central1
  _REPOSITORY: cloud-run-source-deploy
  _TAG: manual
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1800s
