steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - services/api/Dockerfile
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/habiwatch/cloud-run-source-deploy/demodirector-api:latest
